Add success message and better progress bars

diff --git a/asdf.install b/asdf.install
--- a/asdf.install
+++ b/asdf.install
@@ -2,8 +2,9 @@
 
 set -e
 
-ERR="[38;5;9m"
-CLR="[0m"
+AVER="\033[38;5;185m"
+DENY="\033[38;5;9m"
+CLR="\033[0m"
 
 asdf_script='https://github.com/briskconfig/get-asdf/raw/refs/heads/release/asdf.sh'
 grab_latest='https://github.com/BriskBear/profile.d/raw/refs/heads/release/grab_latest.sh'
@@ -14,13 +15,13 @@ XP=$HOME/.local/etc/profile.d
 # Prefer curl else find wget
 if [[ `curl 2>/dev/null` == 127 ]]
 then [[ `wget 2>/dev/null` == 127 ]]                                                   \
-  && ( echo -e "${ERR}Error: Install 'curl' or 'wget' and try again.${CLR}" ; exit 2 ) \
+  && ( echo -e "${DENY}Error: Install 'curl' or 'wget' and try again.${CLR}" ; exit 2 ) \
   || web='wget -S'
 else web='curl -#L'
 fi
 
 # Create user's .local directories for standard profile
-mkdir -vp ~/.local/{bin,etc/profile.d,share/asdf}
+mkdir -p ~/.local/{bin,etc/profile.d,share/asdf}
 
 `${web} ${grab_latest} > $XP/grab_latest.sh`
 . $XP/grab_latest.sh
@@ -30,7 +31,8 @@ pushd $HOME &>/dev/null
   # Download and Extract asdf binary to the path
   pushd .local/bin &>/dev/null
     grab-latest asdf-vm/asdf
-    curl -#Lo $XP/asdf.sh $asdf_script
+    printf "\033[1A\033[0G\033[0K"
+    ${web} $asdf_script > $XP/asdf.sh
     printf "\033[1A\033[0G\033[0K"
   popd &>/dev/null
 
@@ -40,3 +42,5 @@ pushd $HOME &>/dev/null
 
   . .bashrc  # Load newly added environment variables + completion
 popd &>/dev/null
+
+echo -e "${AVER}asdf-vm installed! use \`. ~/.bashrc\` to load${CLR}"
